apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: pod-restarter
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: pod-restarter
    repoURL: git@github.com:windyakin/k8s-application-manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
