apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-restarter
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: pod-restarter
          restartPolicy: Never
          containers:
            - name: pod-restarter
              image: bitnami/kubectl:latest
              command:
                - /pod-restarter.sh
              volumeMounts:
                - name: pod-restarter
                  mountPath: /pod-restarter.sh
                  subPath: pod-restarter.sh
          volumes:
            - name: pod-restarter
              configMap:
                name: pod-restarter
                items:
                  - key: pod-restarter.sh
                    path: pod-restarter.sh
                    mode: 0755
