apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 173n-town
spec:
  secretStoreRef:
    kind: SecretStore
    name: 173n-town
  target:
    name: 173n-town
  data:
    - secretKey: TOWN_USER
      remoteRef:
        key: TOWN_USER
    - secretKey: TOWN_PASS
      remoteRef:
        key: TOWN_PASS
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: SLACK_WEBHOOK_URL
