apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: 173n-town
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: external-secrets-173n-town
            key: doppler-token
