apiVersion: batch/v1
kind: CronJob
metadata:
  name: kosen-website-crawler
spec:
  schedule: "30 22 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kosen-website-crawler
              image: kosen-website-crawler
              imagePullPolicy: Always
              command:
                - npm
                - run
                - start
              env:
                - name: TZ
                  value: Asia/Tokyo
                - name: S3
                  value: 'true'
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: kosen-website-crawler
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kosen-website-crawler
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_S3_BUCKET_REGION
                  value: ap-northeast-1
                - name: AWS_S3_BUCKET_NAME
                  value: kosen-screenshot
