apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: kosen-website-crawler
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB0QlnyjCQFtXv0rTwuOa5+0V4ivPst6DtRuO8SQH7Id2/zP0g0W9BOHVWuAjPK4fjjgvyF9YunWg7WRMtcex1t3y/dgvjcgojPs6zr/SCAcQYM7U2duDqL0wqlSitwxFgg5tmYV2eVszQa6Wofztd8LznP1GZ4kyCcoaKZumbniszu6UFjqHaMBrJralYB4/l6trl7hnlZQKXL0lQc36ueysIsjf0Np/aB+0D0vqHRe+ob+BXDYjTpT0GrsvWss41anP6c1yhrGNM9unfzYzMJWD/5aerpnGXqWqyOOlot9CLD+ZEclwJspJjBcdtlJ7IH0q1DuDAq/fXp6U+oOHVZoVkEih1A/bX1GyQvjbzIheM1avYk9ySQt9+DN4ieoM0kj6L64+etd5jFSzTMShZ9ps5/rYUEu2u5ER0RwS9uTxtSNIGNIfeyXrsf+hZXjivJdJnxSIwUhVLottfnHVKn2HM3/zpUJXX4jTvqGhKhBkv2WsqPQceAsMU8nN3JF+BXAPFRe219mmqBZxLS4wXKs0c5XxdyyAlRcUf5RwDxGgGRO+FNNKwB0YV3iPaWB5qHz7nU4pxaedkdCjQHfi0VB4mAWa3lbylIJrPfVBF9VMAq2xDy+P0m/Okr8GmDBWDBC8KBggcFsRKZbcnqMfaLZpFwU/EktDxCSqFRnGiWeFrHAvOMMYcy/nzIGEhFbOu003b0e9AvWjkW0nuUeBNOlZEIzw==
    AWS_SECRET_ACCESS_KEY: AgCHWXH8KtCPqWhDnDArowNVRc0b8lglSV0Qm0r9P70w4iIxhPFmCrYtSAyaWAo5zo/cvLMksXY2uEhRksgkF4MG9nU9OJo8ldQ76GBOcJSDlACxdfAVXKr22/vZarywo1qUcP1ExZWhMYBZbxPf6V/ka51AkJ2FngEcx3kz4ZgP4fs3ZgySUNWMNyETqpUXkoLr00ggFS/t43pFIVZMYQKOKE3Ajmwju8UrsCeoVH/S1Nl/sWwk1Ya+ywZBXxbO/8LqXBDzaflUqxgt5xGGqNDWmbzuLrSaD2qgzfk2ZgEDqABrOAUS6bSRt3OMAo00Mj/dAoeZkMvzrJJz+He5PfU9hljNnHvMllwv9Zw8olSlyS92EoJIJcJrh20NBORhD0gQ5p2tT5t5Buxes13S8x13CC3QplDguG7HOovicn1QUwcKJKheXt7gY37P8nTYaon+gryKgF2qFSF3+V0t8AjIJUzGq+WVhhJaWbymFgr/Yl6JWC4lpo5HNPprSrkKSNsXqZbWCWnRRqkj6TRVa4klk1IgJ8u9z9JfaVYa2BZtl+MvvM4uMorg8vJ4t02LLG+KyUJwgA8r8sHE0XgRIIymyNv1+VihGQnibKLXOSC5gQvEd9IbavoIO1oN9EHuSaasvqW0dtrh5nXJyR8crlxtemsxYq1eQnxvBqTVVjp1NIAtkCHEay9k6EqhEQU1+jlNSLCE9ONkYJO7uS8ULK74GaCBQhPCCG0+FahulYtVeMytoKgLx05x
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: kosen-website-crawler

